// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	proto/user.proto

It has these top-level messages:
	TokenCheckRequest
	TokenCheckResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenCheckRequest struct {
	JwtToken string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken" json:"jwt_token,omitempty"`
}

func (m *TokenCheckRequest) Reset()                    { *m = TokenCheckRequest{} }
func (m *TokenCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenCheckRequest) ProtoMessage()               {}
func (*TokenCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TokenCheckRequest) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type TokenCheckResponse struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *TokenCheckResponse) Reset()                    { *m = TokenCheckResponse{} }
func (m *TokenCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenCheckResponse) ProtoMessage()               {}
func (*TokenCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TokenCheckResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TokenCheckResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenCheckRequest)(nil), "user.TokenCheckRequest")
	proto.RegisterType((*TokenCheckResponse)(nil), "user.TokenCheckResponse")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x03, 0x33, 0x85, 0x58, 0x40, 0x6c, 0x25, 0x03, 0x2e,
	0xc1, 0x90, 0xfc, 0xec, 0xd4, 0x3c, 0xe7, 0x8c, 0xd4, 0xe4, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x69, 0x2e, 0xce, 0xac, 0xf2, 0x92, 0xf8, 0x12, 0x90, 0x84, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x47, 0x56, 0x79, 0x09, 0x58, 0xa1, 0x92, 0x17, 0x97, 0x10, 0xb2, 0x8e,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x71, 0x2e, 0x76, 0x90, 0x79, 0xf1, 0x99, 0x29, 0x50,
	0x0d, 0x6c, 0x20, 0xae, 0x67, 0x0a, 0xc8, 0x2c, 0xb0, 0x44, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13,
	0xc4, 0x2c, 0x90, 0x80, 0x5f, 0x62, 0x6e, 0xaa, 0x91, 0x27, 0x17, 0x4b, 0x68, 0x71, 0x6a, 0x91,
	0x90, 0x23, 0x17, 0x17, 0xc2, 0x4c, 0x21, 0x71, 0x3d, 0xb0, 0x33, 0x31, 0xdc, 0x25, 0x25, 0x81,
	0x29, 0x01, 0xb1, 0x5e, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x2b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x0b, 0x4e, 0x37, 0x0e, 0xe9, 0x00, 0x00, 0x00,
}
